spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/datacom}
    username: ${DB_USERNAME:datacom}
    password: ${DB_PASSWORD:datacom}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: SESSION

datacom:
  cors:
    allowed-origins: ${FRONT_ORIGINS:http://localhost:5173}
