name: cd

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v7
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/baptiste-fournel/datacom:latest
            ghcr.io/baptiste-fournel/datacom:${{ github.sha }}
